#!/usr/bin/env sh

# Install Homebrew (https://brew.sh/)
brew help || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew update

# Install packages using Homebrew (https://formulae.brew.sh/formula/FORMULAE_NAME)
brew install ack                                                  # ack is a grep-like search tool optimized for source code (https://github.com/beyondgrep/ack3/)
brew install antigen                                              # The plugin manager for zsh (https://github.com/zsh-users/antigen)
brew install cmake                                                # CMake is an open-source, cross-platform family of tools designed to build, test and package software (https://cmake.org/)
brew install cmatrix                                              # Terminal based "The Matrix" like implementation (https://github.com/abishekvashok/cmatrix)
brew install cowsay                                               # Let the cow talk (https://github.com/schacon/cowsay)
brew install deno                                                 # A secure JavaScript and TypeScript runtime (https://github.com/denoland/deno)
brew install figlet                                               # FIGlet is a program for making large letters out of ordinary text (http://www.figlet.org/)
brew install fortune                                              # Fortune CLI (https://gist.github.com/zlorb/4a3eff8981fcec8ca1c7)
brew install fzf                                                  # A command-line fuzzy finder (https://github.com/junegunn/fzf)
brew install git-flow                                             # Git workflow (https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)
brew install github/gh/gh                                         # GitHub’s official command line tool (https://github.com/cli/cli)
brew install htop                                                 # Htop is an interactive text-mode process viewer for Unix systems. It aims to be a better 'top' (https://github.com/hishamhm/htop)
brew install joplin                                               # Open source note taking and to-do application (https://github.com/laurent22/joplin)
brew install jq                                                   # Command-line JSON processor (https://github.com/stedolan/jq)
brew install koekeishiya/formulae/skhd                            # Simple hotkey daemon for macOS (https://github.com/koekeishiya/skhd)
brew install koekeishiya/formulae/yabai                           # A tiling window manager for macOS based on binary space partitioning (https://github.com/koekeishiya/yabai)
brew install links                                                # Terminal based browser (http://links.twibright.com/)
brew install lolcat                                               # Rainbows and unicorns (https://github.com/busyloop/lolcat)
brew install neovim                                               # Vim-fork focused on extensibility and usability (https://github.com/neovim/neovim)
brew install node                                                 # Node.js® is a JavaScript runtime built on Chrome's V8 JavaScript engine (https://nodejs.org/en/)
brew install pastel                                               # A command-line tool to generate, analyze, convert and manipulate colors (https://github.com/sharkdp/pastel)
brew install pipes-sh                                             # Animated pipes terminal screensaver (https://github.com/pipeseroni/pipes.sh)
brew install postgresql                                           # Free and open-source relational database (https://github.com/postgres/postgres/)
brew install putty                                                # SSH client (https://github.com/github/putty)
brew install python3                                              # Python is a programming language that lets you work quickly and integrate systems more effectively (https://www.python.org/)
brew install ranger                                               # A VIM-inspired filemanager for the console (https://github.com/ranger/ranger)
brew install rbenv                                                # Groom your app’s Ruby environment (https://github.com/rbenv/rbenv)
brew install sl                                                   # SL(1): Cure your bad habit of mistyping (https://github.com/mtoyoda/sl)
brew install stow                                                 # GNU Stow is a symlink farm manager (https://www.gnu.org/software/stow/)
brew install terminal-notifier                                    # Send User Notifications on macOS from the command-line (https://github.com/julienXX/terminal-notifier)
brew install tmux                                                 # tmux source code (https://github.com/tmux/tmux)
brew install tree                                                 # Display directories as trees (with optional color/HTML output) (https://formulae.brew.sh/formula/tree)
brew install yarn                                                 # Fast, reliable, and secure dependency management (https://github.com/yarnpkg/yarn)
brew install zsh                                                  # Zsh is a shell designed for interactive use (http://www.zsh.org/)
brew cask install beaker-browser                                  # An experimental peer-to-peer Web browser (https://github.com/beakerbrowser/beaker)
brew cask install brave-browser                                   # Next generation Brave browser for macOS, Windows, Linux, and eventually Android (https://github.com/brave/brave-browser)
brew cask install figma                                           # Collaborative interface design tool (https://github.com/figma)
brew cask install firefox                                         # Mozilla Firefox Browser (https://github.com/mozilla)
brew cask install google-chrome                                   # Google Chrome Browser (https://www.google.com/intl/en_in/chrome/)
brew cask install graphiql                                        # GraphiQL & the GraphQL LSP Reference Ecosystem for building browser & IDE tools (https://github.com/graphql/graphiql)
brew cask install hyper                                           # A terminal built on web technologies (https://github.com/zeit/hyper)
brew cask install insomnia                                        # Cross-platform HTTP and GraphQL Client (https://github.com/Kong/insomnia)
brew cask install keycastr                                        # KeyCastr, an open-source keystroke visualizer (https://github.com/keycastr/keycastr)
brew cask install motrix                                          # A full-featured download manager (https://github.com/agalwood/Motrix)
brew cask install qutebrowser                                     # A keyboard-driven, vim-like browser based on PyQt5 (https://github.com/qutebrowser/qutebrowser)
brew cask install typora                                          # Markdown Reader (https://github.com/typora/)
brew cask install vlc                                             # VLC media player (https://github.com/videolan/vlc)
brew cask install vscodium                                        # Binary releases of VS Code without MS branding/telemetry/licensing (https://github.com/VSCodium/vscodium)
brew install php@7.3; brew install libidn2; brew install libpsl;  # The PHP Interpreter (https://github.com/php/php-src)
brew tap heroku/brew && brew install heroku                       # Heroku CLI (https://github.com/heroku/cli)
brew tap homebrew/cask-fonts                                      # Cask of Fonts (https://github.com/Homebrew/homebrew-cask-fonts)
brew cask install font-fira-code                                  # Monospaced font with programming ligatures (https://github.com/tonsky/FiraCode)
brew cask install font-fontawesome                                # The iconic SVG, font, and CSS toolkit (https://github.com/FortAwesome/Font-Awesome)
terminal-notifier -title 'Installing' -message 'Brew apps have been installed.'

# Cleanup for Homebrew (https://brew.sh/)
brew cleanup
terminal-notifier -title 'Installing' -message 'Brew has been cleaned.'

