gaps:
  inner_gap: 10
  outer_gap: 10

bar:
  height: 30
  position: "top"
  opacity: 1.0
  background: "#101010"
  foreground: "white"
  font_family: "FuraMono Nerd Font"
  font_size: "13"
  padding: "1 6 1 6"
  components_left:
    - type: "workspaces"
      focused_workspace_background: "#8192B3"
      displayed_workspace_background: "#42403e"
      default_workspace_background: "#101010"
  components_right:
    - type: "clock"
      time_formatting: "hh:mm tt  ddd MMM d"

workspaces:
  - name: 1
    display_name: ""
    bind_to_monitor: 1
  - name: 2
    display_name: ""
  - name: 3
    display_name: ""
  - name: 4
    display_name: "ﴘ"
  - name: 5
    display_name: ""
  - name: 6
    display_name: ""
  - name: 7
    display_name: ""
  - name: 8
    display_name: ""
  - name: 9
    display_name: "ﭮ"

window_rules:
  # Task Manager requires admin privileges to manage and should be ignored unless running
  # the WM as admin.
  - command: "ignore"
    match_process_name: "Taskmgr"

  # Launches system dialogs as floating by default (eg. File Explorer save/open dialog).
  - command: "set floating"
    match_class_name: "#32770"

  # Some applications (eg. Steam) have borders that extend past the normal border size.
  - command: "resize borders 0px -7px -7px -7px"
    match_process_name: "steam"

keybindings:
  - command: "focus left"
    bindings: ["LMenu+H", "LMenu+Left"]

  - command: "focus right"
    bindings: ["LMenu+L", "LMenu+Right"]

  - command: "focus up"
    bindings: ["LMenu+K", "LMenu+Up"]

  - command: "focus down"
    bindings: ["LMenu+J", "LMenu+Down"]

  - command: "move left"
    bindings: ["LMenu+Shift+H", "LMenu+Shift+Left"]

  - command: "move right"
    bindings: ["LMenu+Shift+L", "LMenu+Shift+Right"]

  - command: "move up"
    bindings: ["LMenu+Shift+K", "LMenu+Shift+Up"]

  - command: "move down"
    bindings: ["LMenu+Shift+J", "LMenu+Shift+Down"]

  - command: "resize width -2%"
    binding: "LMenu+U"

  - command: "resize width +2%"
    binding: "LMenu+P"

  - command: "resize height +2%"
    binding: "LMenu+O"

  - command: "resize height -2%"
    binding: "LMenu+I"

  - command: "layout horizontal"
    binding: "LMenu+Shift+V"

  - command: "layout vertical"
    binding: "LMenu+V"

  - command: "toggle focus mode"
    binding: "LMenu+Space"

  - command: "toggle floating"
    binding: "LMenu+Shift+Space"

  - command: "set minimized"
    binding: "LMenu+M"

  - command: "toggle maximized"
    binding: "LMenu+X"

  - command: "close"
    binding: "LMenu+Shift+Q"

  - command: "exit wm"
    binding: "LMenu+Shift+E"

  - command: "reload config"
    binding: "LMenu+Shift+R"

  # Launch CMD terminal (Alternatively `exec wt` or `exec %ProgramFiles%/Git/git-bash.exe`
  # to start Windows Terminal and Git Bash respectively.
  - command: "exec wt"
    binding: "LMenu+Enter"

  - command: "focus workspace 1"
    binding: "LMenu+1"

  - command: "focus workspace 2"
    binding: "LMenu+2"

  - command: "focus workspace 3"
    binding: "LMenu+3"

  - command: "focus workspace 4"
    binding: "LMenu+4"

  - command: "focus workspace 5"
    binding: "LMenu+5"

  - command: "focus workspace 6"
    binding: "LMenu+6"

  - command: "focus workspace 7"
    binding: "LMenu+7"

  - command: "focus workspace 8"
    binding: "LMenu+8"

  - command: "focus workspace 9"
    binding: "LMenu+9"

  - commands: ["move to workspace 1", "focus workspace 1"]
    binding: "LMenu+Shift+1"

  - commands: ["move to workspace 2", "focus workspace 2"]
    binding: "LMenu+Shift+2"

  - commands: ["move to workspace 3", "focus workspace 3"]
    binding: "LMenu+Shift+3"

  - commands: ["move to workspace 4", "focus workspace 4"]
    binding: "LMenu+Shift+4"

  - commands: ["move to workspace 5", "focus workspace 5"]
    binding: "LMenu+Shift+5"

  - commands: ["move to workspace 6", "focus workspace 6"]
    binding: "LMenu+Shift+6"

  - commands: ["move to workspace 7", "focus workspace 7"]
    binding: "LMenu+Shift+7"

  - commands: ["move to workspace 8", "focus workspace 8"]
    binding: "LMenu+Shift+8"

  - commands: ["move to workspace 9", "focus workspace 9"]
    bindings: ["LMenu+Shift+9"]
