code --install-extension alefragnani.Bookmarks
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension karunamurti.haml
code --install-extension LaurentTreguier.vscode-simple-icons
code --install-extension misogi.ruby-rubocop
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-ssh-explorer
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension noku.rails-run-spec-vscode
code --install-extension octref.vetur
code --install-extension oderwat.indent-rainbow
code --install-extension PKief.material-icon-theme
code --install-extension rebornix.ruby
code --install-extension RobbOwen.synthwave-vscode
code --install-extension robinbentley.sass-indented
code --install-extension ryuta46.multi-command
code --install-extension shyykoserhiy.vscode-spotify
code --install-extension sianglim.slim
code --install-extension Tyriar.sort-lines
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscodevim.vim
code --install-extension waderyan.gitblame
code --install-extension wayou.vscode-todo-highlight
