code --install-extension alefragnani.Bookmarks
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension Equinusocio.vsc-material-theme
code --install-extension karunamurti.haml
code --install-extension LaurentTreguier.vscode-simple-icons
code --install-extension misogi.ruby-rubocop
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension octref.vetur
code --install-extension oderwat.indent-rainbow
code --install-extension rebornix.ruby
code --install-extension robinbentley.sass-indented
code --install-extension Tyriar.sort-lines
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscodevim.vim
code --install-extension wayou.vscode-todo-highlight
