source ~/.files/zsh/env.z.sh
source ~/.files/zsh/config.z.sh
source ~/.files/zsh/colors.z.sh
source ~/.files/zsh/plugins.z.sh
source ~/.files/zsh/dir.z.sh
source ~/.files/zsh/src.z.sh
source ~/.files/zsh/alias.z.sh
source ~/.files/zsh/docker.z.sh
source ~/.files/zsh/projects.z.sh
source ~/.files/zsh/fzf.z.sh
source ~/.files/zsh/node.z.sh
source ~/.files/zsh/ruby.z.sh
source ~/.files/zsh/brew.z.sh
source ~/.files/zsh/adb.z.sh
source ~/.files/zsh/git.z.sh
source ~/.files/zsh/gpg.z.sh
source ~/.files/zsh/tmux.z.sh
source ~/.files/zsh/personal.z.sh
source ~/.files/zsh/work.z.sh
source ~/.files/zsh/start-session.z.sh
source ~/.files/zsh/end-session.z.sh
