codium --install-extension CoenraadS.bracket-pair-colorizer-2
codium --install-extension dbaeumer.vscode-eslint
codium --install-extension eamodio.gitlens
codium --install-extension ExodiusStudios.comment-anchors
codium --install-extension eyhn.vscode-vibrancy
codium --install-extension LaurentTreguier.vscode-simple-icons
codium --install-extension ms-vsliveshare.vsliveshare
codium --install-extension oderwat.indent-rainbow
codium --install-extension rebornix.ruby
codium --install-extension vscodevim.vim
codium --install-extension wingrunr21.vscode-ruby
