codium --install-extension alefragnani.Bookmarks
codium --install-extension christian-kohler.path-intellisense
codium --install-extension CoenraadS.bracket-pair-colorizer-2
codium --install-extension dbaeumer.vscode-eslint
codium --install-extension deerawan.vscode-dash
codium --install-extension eamodio.gitlens
codium --install-extension Equinusocio.vsc-material-theme
codium --install-extension karunamurti.haml
codium --install-extension LaurentTreguier.vscode-simple-icons
codium --install-extension ms-vsliveshare.vsliveshare
codium --install-extension octref.vetur
codium --install-extension oderwat.indent-rainbow
codium --install-extension rebornix.ruby
codium --install-extension Tyriar.sort-lines
codium --install-extension VisualStudioExptTeam.vscodeintellicode
codium --install-extension vscodevim.vim
codium --install-extension wayou.vscode-todo-highlight
codium --install-extension wingrunr21.vscode-ruby
